name: Ejecutar Scraper de FBref y Guardar CSV

on:
  schedule:
    # Ejecuta todos los días a las 10:30 UTC (que son las 12:30 CEST)
    - cron: '30 10 * * *'
  workflow_dispatch: # Permite la ejecución manual

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Puedes usar 3.x o una versión específica

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas lxml html5lib

      - name: Ejecutar script standard_scrape.py
        run: python standard_scrape.py

      - name: Subir artefacto CSV
        uses: actions/upload-artifact@v4
        with:
          name: estadisticas-jugadores-big5
          path: ./data/big5_player_stats.csv
          if-no-files-found: error
